import { LevelConfig, MCQuestion, DialogueTrigger, MonsterType } from './types';

// Monster spawn configurations for each level
export interface MonsterSpawn {
  type: MonsterType;
  count: number;
}

export const LEVEL_MONSTERS: Record<string, MonsterSpawn[]> = {
  forest: [
    { type: 'slime', count: 3 },
    { type: 'bat', count: 2 },
  ],
  clockwork: [
    { type: 'slime', count: 2 },
    { type: 'bat', count: 3 },
    { type: 'shadow', count: 1 },
  ],
  mirror: [
    { type: 'ghost', count: 2 },
    { type: 'shadow', count: 3 },
  ],
};

// Level configurations
export const LEVELS: LevelConfig[] = [
  {
    id: 'prologue',
    name: 'Prologue - Quiet Village',
    backgroundColor: '#1a1a2e',
    groundColor: '#2d4a3e',
    hasBoss: false,
    introTexts: [
      'She finds your message.',
      'The world glitches.',
      'Something feels wrong...',
    ],
  },
  {
    id: 'harsh',
    name: 'Level 1 - The Confused Knight',
    backgroundColor: '#2a1a3e',
    groundColor: '#3d2d4a',
    hasBoss: true,
    bossType: 'harsh',
  },
  {
    id: 'forest',
    name: 'Level 2 - Forest of Lost Paths',
    backgroundColor: '#1a2e1a',
    groundColor: '#2d4a2d',
    hasBoss: false,
    ambientTexts: [
      'Are you sure this is the right way?',
      'Everything looks the same...',
    ],
  },
  {
    id: 'garima',
    name: 'Level 3 - The False Ally',
    backgroundColor: '#1a2e2e',
    groundColor: '#2d4a4a',
    hasBoss: true,
    bossType: 'garima',
  },
  {
    id: 'clockwork',
    name: 'Level 4 - Clockwork Area',
    backgroundColor: '#2e2a1a',
    groundColor: '#4a4a2d',
    hasBoss: false,
    ambientTexts: [
      'Timing is everything.',
      'Too early. Too late.',
    ],
  },
  {
    id: 'parnika',
    name: 'Level 5 - Queen of the Swamp',
    backgroundColor: '#1a2e1a',
    groundColor: '#3d5a2d',
    hasBoss: true,
    bossType: 'parnika',
  },
  {
    id: 'mirror',
    name: 'Level 6 - Mirror Area',
    backgroundColor: '#2e2e2e',
    groundColor: '#4a4a4a',
    hasBoss: false,
    ambientTexts: [
      'Is that... you?',
      'Or is it who you think you are?',
    ],
  },
  {
    id: 'ravin',
    name: 'Level 7 - The Riddler',
    backgroundColor: '#3e2a1a',
    groundColor: '#5a4a2d',
    hasBoss: true,
    bossType: 'ravin',
  },
  {
    id: 'final',
    name: 'Final Level - Evil Castle',
    backgroundColor: '#1a0a0a',
    groundColor: '#3a1a1a',
    hasBoss: true,
    bossType: 'final',
    ambientTexts: [
      'Everything you faced returns.',
      'This ends now.',
    ],
  },
];

// Boss dialogues
export const BOSS_DIALOGUES: Record<string, DialogueTrigger[]> = {
  harsh: [
    { condition: 'intro', text: 'Prepare yourself, warrior!', triggered: false },
    { condition: 'random', text: 'Wait—no—YES—actually—WHAT??', triggered: false },
    { condition: 'random', text: 'Why am I like this??', triggered: false },
    { condition: 'random', text: "Hold on—this wasn't the plan—", triggered: false },
    { condition: 'defeat', text: 'I AM CONFUSED ASF!!!', triggered: false },
  ],
  garima: [
    { condition: 'intro', text: 'I am your best friend!', triggered: false },
    { condition: 'hp_threshold', hpThreshold: 95, text: "Let's hug my best friend!", triggered: false },
    { condition: 'hp_threshold', hpThreshold: 80, text: "See? Together we're unstoppable.", triggered: false },
    { condition: 'hp_threshold', hpThreshold: 50, text: 'I helped you... so why are you so gorgeous?', triggered: false },
    { condition: 'special_unlock', text: '💥 DIARRHEA UNLOCKED 💥', triggered: false },
    { condition: 'defeat', text: "THIS WASN'T THE PLAN—", triggered: false },
  ],
  parnika: [
    { condition: 'intro', text: 'Let me tell you something—', triggered: false },
    { condition: 'random', text: 'Actually—no—listen—', triggered: false },
    { condition: 'random', text: 'WAIT—ONE MORE THING—', triggered: false },
    { condition: 'random', text: "You're not even listening!", triggered: false },
    { condition: 'defeat', text: 'WHY IS NO ONE LISTENING TO ME??', triggered: false },
  ],
  ravin: [
    { condition: 'intro', text: 'Only intellectual elites survive my library.', triggered: false },
    { condition: 'defeat', text: "How... how do you know these? You're... intelligent??", triggered: false },
  ],
  final: [
    { condition: 'intro', text: 'All your struggles end here.', triggered: false },
    { condition: 'hp_threshold', hpThreshold: 50, text: 'Impossible! How are you still standing?', triggered: false },
    { condition: 'defeat', text: 'No... this cannot be...', triggered: false },
  ],
};

// 100 MCQ Questions for Ravin
export const MCQ_QUESTIONS: MCQuestion[] = [
  { question: 'Capital of India is:', options: ['Mumbai', 'New Delhi', 'Kolkata', 'Chennai'], correctIndex: 1 },
  { question: 'National animal of India:', options: ['Lion', 'Elephant', 'Tiger', 'Leopard'], correctIndex: 2 },
  { question: 'National bird of India:', options: ['Peacock', 'Sparrow', 'Eagle', 'Crow'], correctIndex: 0 },
  { question: 'National flower of India:', options: ['Rose', 'Lotus', 'Lily', 'Sunflower'], correctIndex: 1 },
  { question: 'National fruit of India:', options: ['Banana', 'Apple', 'Mango', 'Orange'], correctIndex: 2 },
  { question: 'Who is known as the Father of the Nation?', options: ['Nehru', 'Patel', 'Gandhi', 'Bose'], correctIndex: 2 },
  { question: 'India got independence in:', options: ['1945', '1946', '1947', '1950'], correctIndex: 2 },
  { question: 'Republic Day is celebrated on:', options: ['15 August', '26 January', '2 October', '14 November'], correctIndex: 1 },
  { question: 'Independence Day is celebrated on:', options: ['26 January', '2 October', '15 August', '5 September'], correctIndex: 2 },
  { question: 'Gandhi Jayanti is on:', options: ['15 August', '26 January', '2 October', '14 November'], correctIndex: 2 },
  { question: 'Prime Minister of India is:', options: ['President', 'Governor', 'Prime Minister', 'Chief Justice'], correctIndex: 2 },
  { question: 'Head of the State in India:', options: ['Prime Minister', 'President', 'Vice President', 'Governor'], correctIndex: 1 },
  { question: 'Number of states in India (2025):', options: ['27', '28', '29', '30'], correctIndex: 1 },
  { question: 'Number of Union Territories in India:', options: ['6', '7', '8', '9'], correctIndex: 2 },
  { question: 'Indian Parliament has:', options: ['One house', 'Two houses', 'Three houses', 'Four houses'], correctIndex: 1 },
  { question: 'Lower House of Parliament:', options: ['Rajya Sabha', 'Vidhan Sabha', 'Lok Sabha', 'Supreme Court'], correctIndex: 2 },
  { question: 'Upper House of Parliament:', options: ['Lok Sabha', 'Vidhan Sabha', 'Rajya Sabha', 'Cabinet'], correctIndex: 2 },
  { question: 'Supreme law of India:', options: ['IPC', 'Constitution', 'Parliament Act', 'Judiciary'], correctIndex: 1 },
  { question: 'Constitution of India came into force in:', options: ['1947', '1948', '1949', '1950'], correctIndex: 3 },
  { question: 'Chairman of Rajya Sabha:', options: ['Prime Minister', 'President', 'Vice President', 'Speaker'], correctIndex: 2 },
  { question: 'Largest state by area:', options: ['Maharashtra', 'Uttar Pradesh', 'Rajasthan', 'Madhya Pradesh'], correctIndex: 2 },
  { question: 'Largest state by population:', options: ['Bihar', 'Maharashtra', 'West Bengal', 'Uttar Pradesh'], correctIndex: 3 },
  { question: 'Smallest state by area:', options: ['Sikkim', 'Goa', 'Tripura', 'Manipur'], correctIndex: 1 },
  { question: 'Longest river in India:', options: ['Yamuna', 'Brahmaputra', 'Ganga', 'Godavari'], correctIndex: 2 },
  { question: 'Holy river of India:', options: ['Narmada', 'Kaveri', 'Ganga', 'Krishna'], correctIndex: 2 },
  { question: 'National anthem of India:', options: ['Vande Mataram', 'Jana Gana Mana', 'Sare Jahan Se Accha', 'Saare Jahan'], correctIndex: 1 },
  { question: 'National song of India:', options: ['Jana Gana Mana', 'Vande Mataram', 'Ae Mere Watan', 'Des Rangila'], correctIndex: 1 },
  { question: 'Currency of India:', options: ['Dollar', 'Pound', 'Rupee', 'Taka'], correctIndex: 2 },
  { question: 'Symbol of Indian Rupee:', options: ['$', '€', '₹', '¥'], correctIndex: 2 },
  { question: 'First Prime Minister of India:', options: ['Gandhi', 'Patel', 'Nehru', 'Bose'], correctIndex: 2 },
  { question: 'First President of India:', options: ['Rajendra Prasad', 'Nehru', 'Radhakrishnan', 'Patel'], correctIndex: 0 },
  { question: 'First woman Prime Minister of India:', options: ['Sonia Gandhi', 'Pratibha Patil', 'Indira Gandhi', 'Sushma Swaraj'], correctIndex: 2 },
  { question: 'First woman President of India:', options: ['Indira Gandhi', 'Pratibha Patil', 'Droupadi Murmu', 'Sarojini Naidu'], correctIndex: 1 },
  { question: 'Current President of India (2025):', options: ['Pranab Mukherjee', 'Ram Nath Kovind', 'Droupadi Murmu', 'Rajnath Singh'], correctIndex: 2 },
  { question: 'Highest court in India:', options: ['High Court', 'District Court', 'Supreme Court', 'Lok Adalat'], correctIndex: 2 },
  { question: 'National sport of India (commonly accepted):', options: ['Cricket', 'Hockey', 'Kabaddi', 'Football'], correctIndex: 1 },
  { question: 'Famous monument in Agra:', options: ['Qutub Minar', 'Red Fort', 'Taj Mahal', 'Hawa Mahal'], correctIndex: 2 },
  { question: 'Qutub Minar is in:', options: ['Agra', 'Jaipur', 'Delhi', 'Bhopal'], correctIndex: 2 },
  { question: 'Hawa Mahal is in:', options: ['Udaipur', 'Jaipur', 'Jodhpur', 'Ajmer'], correctIndex: 1 },
  { question: "India's space agency:", options: ['DRDO', 'ISRO', 'BARC', 'HAL'], correctIndex: 1 },
  { question: 'First satellite of India:', options: ['Aryabhata', 'Bhaskara', 'Rohini', 'INSAT'], correctIndex: 0 },
  { question: 'Chandrayaan mission is related to:', options: ['Sun', 'Mars', 'Moon', 'Jupiter'], correctIndex: 2 },
  { question: 'Mangalyaan is related to:', options: ['Venus', 'Mars', 'Moon', 'Sun'], correctIndex: 1 },
  { question: 'National tree of India:', options: ['Banyan', 'Neem', 'Peepal', 'Mango'], correctIndex: 0 },
  { question: 'National river of India:', options: ['Yamuna', 'Ganga', 'Godavari', 'Kaveri'], correctIndex: 1 },
  { question: 'Founder of Buddhism:', options: ['Mahavira', 'Buddha', 'Ashoka', 'Kabir'], correctIndex: 1 },
  { question: 'Founder of Jainism:', options: ['Buddha', 'Ashoka', 'Mahavira', 'Rama'], correctIndex: 2 },
  { question: 'Ramayana was written by:', options: ['Ved Vyasa', 'Tulsidas', 'Valmiki', 'Kalidas'], correctIndex: 2 },
  { question: 'Mahabharata was written by:', options: ['Valmiki', 'Ved Vyasa', 'Kalidas', 'Kabir'], correctIndex: 1 },
  { question: 'Yoga originated in:', options: ['China', 'India', 'Nepal', 'Tibet'], correctIndex: 1 },
  { question: 'International Yoga Day:', options: ['5 June', '21 June', '15 August', '2 October'], correctIndex: 1 },
  { question: 'Hindi is written in which script?', options: ['Roman', 'Urdu', 'Devanagari', 'Tamil'], correctIndex: 2 },
  { question: 'English came to India during:', options: ['Mughals', 'French rule', 'British rule', 'Portuguese rule'], correctIndex: 2 },
  { question: 'National calendar of India:', options: ['Gregorian', 'Islamic', 'Saka', 'Hindu'], correctIndex: 2 },
  { question: 'Goa was liberated in:', options: ['1947', '1950', '1961', '1971'], correctIndex: 2 },
  { question: 'Green Revolution is related to:', options: ['Industry', 'Agriculture', 'Transport', 'Education'], correctIndex: 1 },
  { question: 'White Revolution is related to:', options: ['Milk', 'Fish', 'Wheat', 'Oil'], correctIndex: 0 },
  { question: 'Father of Indian Constitution:', options: ['Nehru', 'Gandhi', 'Ambedkar', 'Patel'], correctIndex: 2 },
  { question: 'Planning Commission was replaced by:', options: ['RBI', 'NITI Aayog', 'Finance Ministry', 'Parliament'], correctIndex: 1 },
  { question: 'Election Commission of India is:', options: ['Private body', 'NGO', 'Constitutional body', 'Company'], correctIndex: 2 },
  { question: 'Voting age in India:', options: ['16', '17', '18', '21'], correctIndex: 2 },
  { question: 'Indian flag has how many colors?', options: ['2', '3', '4', '5'], correctIndex: 1 },
  { question: 'Ashoka Chakra has how many spokes?', options: ['12', '18', '24', '36'], correctIndex: 2 },
  { question: 'Blue color in flag represents:', options: ['Peace', 'Courage', 'Dharma', 'Growth'], correctIndex: 2 },
  { question: 'Saffron color represents:', options: ['Peace', 'Sacrifice', 'Truth', 'Prosperity'], correctIndex: 1 },
  { question: 'Largest desert in India:', options: ['Thar', 'Sahara', 'Kalahari', 'Gobi'], correctIndex: 0 },
  { question: 'Western Ghats are in:', options: ['East India', 'North India', 'South India', 'Central India'], correctIndex: 2 },
  { question: 'Indian Ocean is to the:', options: ['North of India', 'South of India', 'East of India', 'West of India'], correctIndex: 1 },
  { question: 'Bay of Bengal is to the:', options: ['West', 'North', 'East', 'South'], correctIndex: 2 },
  { question: 'Arabian Sea is to the:', options: ['East', 'North', 'West', 'South'], correctIndex: 2 },
  { question: 'Who built Taj Mahal?', options: ['Akbar', 'Babur', 'Shah Jahan', 'Aurangzeb'], correctIndex: 2 },
  { question: 'Red Fort is in:', options: ['Agra', 'Delhi', 'Jaipur', 'Lucknow'], correctIndex: 1 },
  { question: 'Charminar is in:', options: ['Hyderabad', 'Chennai', 'Bengaluru', 'Pune'], correctIndex: 0 },
  { question: 'Gateway of India is in:', options: ['Goa', 'Mumbai', 'Kochi', 'Kolkata'], correctIndex: 1 },
  { question: 'India is part of which continent?', options: ['Europe', 'Africa', 'Asia', 'Australia'], correctIndex: 2 },
  { question: 'National literacy mission aims to improve:', options: ['Sports', 'Education', 'Health', 'Transport'], correctIndex: 1 },
  { question: 'Public sector banks are owned by:', options: ['Private companies', 'RBI', 'Government', 'Foreign firms'], correctIndex: 2 },
  { question: 'RBI controls:', options: ['Education', 'Defence', 'Money supply', 'Railways'], correctIndex: 2 },
  { question: 'Income tax is collected by:', options: ['State govt', 'Panchayat', 'Central govt', 'Municipality'], correctIndex: 2 },
  { question: 'GST stands for:', options: ['General Sales Tax', 'Goods and Services Tax', 'Gross Sales Tax', 'Government Service Tax'], correctIndex: 1 },
  { question: 'India is a:', options: ['Monarchy', 'Dictatorship', 'Republic', 'Empire'], correctIndex: 2 },
  { question: 'Preamble starts with:', options: ['We the People', 'India is Great', 'Jai Hind', 'Truth Alone Triumphs'], correctIndex: 0 },
  { question: 'Satyameva Jayate means:', options: ['Truth always wins', 'Victory to India', 'Jai Hind', 'Peace forever'], correctIndex: 0 },
  { question: 'National emblem comes from:', options: ['Ashoka Pillar', 'Taj Mahal', 'Red Fort', 'Qutub Minar'], correctIndex: 0 },
  { question: 'Lion Capital is at:', options: ['Delhi', 'Sarnath', 'Patna', 'Agra'], correctIndex: 1 },
  { question: 'Which festival is called Festival of Lights?', options: ['Holi', 'Diwali', 'Eid', 'Christmas'], correctIndex: 1 },
  { question: 'Holi is festival of:', options: ['Lights', 'Colors', 'Flowers', 'Harvest'], correctIndex: 1 },
  { question: 'Eid is celebrated by:', options: ['Hindus', 'Christians', 'Muslims', 'Sikhs'], correctIndex: 2 },
  { question: 'Christmas is celebrated by:', options: ['Buddhists', 'Muslims', 'Christians', 'Jains'], correctIndex: 2 },
  { question: 'Guru Nanak founded:', options: ['Hinduism', 'Buddhism', 'Sikhism', 'Jainism'], correctIndex: 2 },
  { question: 'Sikh holy book:', options: ['Vedas', 'Quran', 'Bible', 'Guru Granth Sahib'], correctIndex: 3 },
  { question: "India's national language is:", options: ['Hindi', 'English', 'No national language', 'Sanskrit'], correctIndex: 2 },
  { question: 'Most widely spoken language in India:', options: ['English', 'Bengali', 'Hindi', 'Tamil'], correctIndex: 2 },
  { question: 'India shares longest border with:', options: ['Pakistan', 'Bangladesh', 'China', 'Nepal'], correctIndex: 2 },
  { question: 'Indian Army Day:', options: ['15 January', '26 January', '4 December', '8 October'], correctIndex: 0 },
  { question: 'Navy Day is celebrated on:', options: ['15 January', '4 December', '8 October', '26 January'], correctIndex: 1 },
  { question: 'Air Force Day is on:', options: ['8 October', '15 August', '26 January', '2 October'], correctIndex: 0 },
  { question: 'Census in India happens every:', options: ['5 years', '8 years', '10 years', '12 years'], correctIndex: 2 },
  { question: "India's time zone:", options: ['GMT', 'IST', 'PST', 'CST'], correctIndex: 1 },
  { question: "India's national motto is:", options: ['Jai Hind', 'Vande Mataram', 'Satyameva Jayate', 'Inquilab Zindabad'], correctIndex: 2 },
];

// Ending texts
export const ENDING_TEXTS = [
  "She didn't just beat the game.",
  'She beat every doubt along the way.',
];
